// Every plugin preview clip, by the plugin's slug on dansplugins.com.
module.exports = {
  'medieval-factions': require('./medieval-factions'),
  'currencies': require('./currencies'),
  'bluemap-medieval-factions': require('./bluemap-medieval-factions'),
  'dans-plugin-manager': require('./dans-plugin-manager'),
  'democracy': require('./democracy'),
  'medieval-roleplay-engine': require('./medieval-roleplay-engine'),
  'fiefs': require('./fiefs'),
  'mailboxes': require('./mailboxes'),
  'simple-skills': require('./simple-skills'),
  'activity-tracker': require('./activity-tracker'),
  'dans-essentials': require('./dans-essentials'),
  'dans-set-home': require('./dans-set-home'),
  'easy-links': require('./easy-links'),
  'medieval-economy': require('./medieval-economy'),
  'nether-access-controller': require('./nether-access-controller'),
  'kdr-tracker': require('./kdr-tracker'),
  'wild-pets': require('./wild-pets'),
  'mini-factions': require('./mini-factions'),
};
