spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dpc}
    username: ${DB_USERNAME:dpc}
    password: ${DB_PASSWORD:dpc}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080

dpc:
  api:
    key: ${DPC_API_KEY:}
